SCR_MissionHeader {
 World "{6D161EF909ABF4A7}Worlds/NML/Dev/NML_Dev_Everon.ent"
 m_sName "NML DEV (Everon)"
 m_sAuthor "NML"
 m_sDescription "No Man's Land local development scenario. DEV only, never published."
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "NML DEV"
 m_iPlayerCount 8
}
