// Regenerates dependencies/candidates/INDEX.md from candidate frontmatter.
// Usage: node tools/candidates-index.mjs          (write INDEX.md)
//        node tools/candidates-index.mjs --check  (CI: fail if INDEX.md is stale)

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DIR = path.join(ROOT, "dependencies", "candidates");
const INDEX = path.join(DIR, "INDEX.md");
const SKIP = ["README.md", "INDEX.md", "_TEMPLATE.md"];

function frontmatter(file)
{
	const m = /^---\r?\n([\s\S]*?)\r?\n---/.exec(fs.readFileSync(file, "utf8"));
	const fm = {};
	for (const line of (m ? m[1] : "").split(/\r?\n/))
	{
		const kv = /^([A-Za-z][\w-]*):\s*(.*)$/.exec(line);
		if (kv)
			fm[kv[1]] = kv[2].replace(/^["']|["']$/g, "").trim();
	}
	return fm;
}

const rows = fs.readdirSync(DIR)
	.filter((f) => f.endsWith(".md") && !SKIP.includes(f))
	.map((f) => ({ file: f, ...frontmatter(path.join(DIR, f)) }))
	.sort((a, b) => (a.category || "").localeCompare(b.category || "") || (a.name || "").localeCompare(b.name || ""));

const esc = (s) => String(s || "").replace(/\|/g, "\\|");
const lines = [
	"# Candidate index",
	"",
	"Generated by `node tools/candidates-index.mjs`. Do not edit by hand.",
	"",
	`${rows.length} candidate file(s). Batch intake notes live in [intake/](intake/).`,
	"",
	"| Candidate | Status | Category | Capabilities | Workshop ID |",
	"|---|---|---|---|---|",
	...rows.map((r) => `| [${esc(r.name)}](${r.file}) | ${esc(r.status)} | ${esc(r.category)} | ${esc(r.capabilities)} | ${esc(r.workshopId)} |`),
	"",
];
const next = lines.join("\n");

if (process.argv.includes("--check"))
{
	const cur = fs.existsSync(INDEX) ? fs.readFileSync(INDEX, "utf8").replace(/\r\n/g, "\n") : "";
	if (cur !== next)
	{
		console.log("dependencies/candidates/INDEX.md is stale. Run: node tools/candidates-index.mjs");
		process.exitCode = 1;
	}
	else
	{
		console.log("Candidate index is up to date.");
	}
}
else
{
	fs.writeFileSync(INDEX, next);
	console.log(`Wrote ${path.relative(ROOT, INDEX)} (${rows.length} candidates).`);
}
